// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listClips: (source: string | null, contentType: string | null, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("list_clips", { source, contentType, limit })),
	listPinnedClips: () => typedError<LocalClip[], string>(__TAURI_INVOKE("list_pinned_clips")),
	pinClip: (id: string, note: string | null) => typedError<null, string>(__TAURI_INVOKE("pin_clip", { id, note })),
	unpinClip: (id: string) => typedError<null, string>(__TAURI_INVOKE("unpin_clip", { id })),
	searchClips: (query: string, limit: number | null) => typedError<LocalClip[], string>(__TAURI_INVOKE("search_clips", { query, limit })),
	getSources: () => typedError<SourceInfo[], string>(__TAURI_INVOKE("get_sources")),
	deleteClip: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_clip", { id })),
	/**
	 *  Explicitly send an already-captured local clip to the relay (and thus to
	 *  the user's other devices). This is the ONLY path by which a clip leaves
	 *  the device — the clipboard monitor never pushes.
	 * 
	 *  `target_device_id` is optional: `None` (null from TypeScript) broadcasts
	 *  to all of the user's devices; `Some(id)` restricts delivery to that device.
	 */
	sendClip: (id: string, targetDeviceId: string | null) => typedError<null, string>(__TAURI_INVOKE("send_clip", { id, targetDeviceId })),
	/**
	 *  Send whatever is currently on the system clipboard to the user's devices.
	 *  Bound to the opt-in send shortcut. Returns Ok(()) on success, Err on
	 *  empty/unsupported clipboard or push failure.
	 */
	sendCurrentClipboard: () => typedError<null, string>(__TAURI_INVOKE("send_current_clipboard")),
	getClipCount: () => typedError<number, string>(__TAURI_INVOKE("get_clip_count")),
	getConfigInfo: () => __TAURI_INVOKE<ConfigInfo>("get_config_info"),
	getSourceAutoCopy: (source: string) => typedError<boolean, string>(__TAURI_INVOKE("get_source_auto_copy", { source })),
	setSourceAutoCopy: (source: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_source_auto_copy", { source, enabled })),
	getAllSourceSettings: () => typedError<SourceSetting[], string>(__TAURI_INVOKE("get_all_source_settings")),
	getSourceAlertEnabled: (source: string) => typedError<boolean, string>(__TAURI_INVOKE("get_source_alert_enabled", { source })),
	setSourceAlertEnabled: (source: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_source_alert_enabled", { source, enabled })),
	getAllSourceAlertSettings: () => typedError<SourceAlertSetting[], string>(__TAURI_INVOKE("get_all_source_alert_settings")),
	markClipCopied: (id: string) => typedError<null, string>(__TAURI_INVOKE("mark_clip_copied", { id })),
	copyClipToClipboard: (content: string) => typedError<null, string>(__TAURI_INVOKE("copy_clip_to_clipboard", { content })),
	copyImageToClipboard: (clipId: string) => typedError<null, string>(__TAURI_INVOKE("copy_image_to_clipboard", { clipId })),
	saveImageToFile: (clipId: string) => typedError<string | null, string>(__TAURI_INVOKE("save_image_to_file", { clipId })),
	/**
	 *  Restore focus to the app that was frontmost before Cinch was shown, then hide the
	 *  Cinch window. On non-macOS platforms this simply hides the window.
	 */
	focusPreviousApp: () => typedError<null, string>(__TAURI_INVOKE("focus_previous_app")),
	listDevices: () => typedError<Device[], string>(__TAURI_INVOKE("list_devices")),
	setDeviceNickname: (deviceId: string, nickname: string) => typedError<null, string>(__TAURI_INVOKE("set_device_nickname", { deviceId, nickname })),
	revokeDevice: (deviceId: string) => typedError<null, string>(__TAURI_INVOKE("revoke_device", { deviceId })),
	getExcludedApps: () => typedError<string[], string>(__TAURI_INVOKE("get_excluded_apps")),
	setExcludedApps: (apps: string[]) => typedError<null, string>(__TAURI_INVOKE("set_excluded_apps", { apps })),
	getRetentionConfig: () => typedError<RetentionConfig, string>(__TAURI_INVOKE("get_retention_config")),
	setRetentionConfig: (localDays: number, remoteDays: number) => typedError<null, string>(__TAURI_INVOKE("set_retention_config", { localDays, remoteDays })),
	/**
	 *  Return the number of clips that would be deleted if `local_retention_days`
	 *  were set to `days` right now. Backs the Settings-pane retroactive-purge
	 *  confirmation dialog.
	 * 
	 *  `days` is clamped to `[MIN_RETENTION_DAYS, MAX_RETENTION_DAYS]` (T-06-02).
	 */
	previewRetentionChange: (days: number) => typedError<number, string>(__TAURI_INVOKE("preview_retention_change", { days })),
	/**
	 *  Wipe every clip row + cascade-delete media files. Returns the number of
	 *  rows deleted. Used by the "Clear local history" Settings button (PRV-03).
	 */
	clearLocalHistory: () => typedError<number, string>(__TAURI_INVOKE("clear_local_history")),
	saveConfig: (relayUrl: string, token: string) => typedError<null, string>(__TAURI_INVOKE("save_config", { relayUrl, token })),
	getWsStatus: () => __TAURI_INVOKE<string>("get_ws_status"),
	getGlobalShortcut: () => typedError<string, string>(__TAURI_INVOKE("get_global_shortcut")),
	setGlobalShortcut: (shortcut: string) => typedError<null, string>(__TAURI_INVOKE("set_global_shortcut", { shortcut })),
	getSendShortcut: () => typedError<string | null, string>(__TAURI_INVOKE("get_send_shortcut")),
	setSendShortcut: (shortcut: string | null) => typedError<null, string>(__TAURI_INVOKE("set_send_shortcut", { shortcut })),
	/**
	 *  Resolve the one-time background-running hint. Marks the hint seen (so it
	 *  never shows again), then either quits the app (`quit = true`,
	 *  `app.exit(0)` — the same path as the tray's "Quit Cinch", which passes the
	 *  `ExitRequested { code: None }` guard in lib.rs) or hides the main window
	 *  (`quit = false`, the normal menu-bar-agent dismissal).
	 */
	resolveBackgroundHint: (quit: boolean) => typedError<null, string>(__TAURI_INVOKE("resolve_background_hint", { quit })),
	// Returns the current AuthState. Used by AuthProvider's initial fetch in React.
	getAuthState: () => __TAURI_INVOKE<AuthState>("get_auth_state"),
	/**
	 *  Returns display-facing identity fields from the active relay profile.
	 * 
	 *  Falls back to all-empty-string `UserProfile` when no profile is configured
	 *  (e.g. before first sign-in) so the frontend can render a sensible
	 *  unauthenticated state without a `Result` branch.
	 */
	getUserProfile: () => __TAURI_INVOKE<UserProfile>("get_user_profile"),
	/**
	 *  Updates the display name for the currently authenticated user.
	 * 
	 *  Validates locally (trim → non-empty → ≤ 64 bytes), POSTs to
	 *  `{relay_url}/auth/display-name`, and refreshes the on-disk config so the
	 *  next `get_user_profile` call returns the updated name.
	 * 
	 *  Returns the name as stored by the relay (trimmed).
	 */
	setDisplayName: (name: string) => typedError<string, string>(__TAURI_INVOKE("set_display_name", { name })),
	/**
	 *  list_auth_providers — fetches `GET {relay}/auth/providers` from the relay.
	 * 
	 *  Lives in Rust because the Tauri WebView's CSP (`connect-src 'self' ipc:`)
	 *  blocks the frontend from issuing a cross-origin `fetch` to relay URLs.
	 *  Returns `[]` on any failure so the dialog can fall back to a generic
	 *  sign-in button without surfacing a transient error during typing.
	 */
	listAuthProviders: (relayUrl: string) => __TAURI_INVOKE<string[]>("list_auth_providers", { relayUrl }),
	/**
	 *  sign_in — browser-based sign-in using device-code polling.
	 * 
	 *  Flow (deep-link-independent):
	 *    1. Transitions to Authenticating{SigningIn}
	 *    2. POSTs to {relay_url}/auth/device-code to get a device_code + verification_uri
	 *    3. Opens verification_uri in the system browser (includes device_code so OAuth
	 *       providers show the right page and the relay can complete the flow)
	 *    4. Returns immediately — a background tokio task polls
	 *       GET {relay_url}/auth/device-code/poll?code={device_code} every 3 seconds
	 *    5. When status == "complete", writes credentials and transitions to Authenticated
	 * 
	 *  The existing cinch://auth/callback deep-link handler in lib.rs still fires as a
	 *  secondary path (legacy self-host servers that skip the device-code completion step).
	 */
	signIn: (relayUrl: string, provider: string | null) => typedError<null, string>(__TAURI_INVOKE("sign_in", { relayUrl, provider })),
	/**
	 *  sign_out — calls POST /auth/device/revoke (best-effort), wipes credentials, transitions to LocalOnly.
	 *  Mirrors the CLI `auth logout` D-10 behavior.
	 */
	signOut: () => typedError<null, string>(__TAURI_INVOKE("sign_out")),
	/**
	 *  retry_auth — bypasses ErrorRecoverable.retry_after_ms and re-attempts the last failing operation.
	 *  For Phase 2 plumbing: resets to LocalOnly and lets the user re-invoke sign_in.
	 *  Phase 3+ will store the last-attempted operation and retry it in place.
	 */
	retryAuth: () => typedError<null, string>(__TAURI_INVOKE("retry_auth")),
	/**
	 *  handle_deeplink — Tauri command for React to invoke when it receives a deep-link URL
	 *  via getCurrent() (cold-start case) or onOpenUrl (fallback for JS-side handling).
	 * 
	 *  Parses the URL, extracts auth params, writes credentials, transitions state,
	 *  and spawns WS client.
	 */
	handleDeeplink: (url: string) => typedError<null, string>(__TAURI_INVOKE("handle_deeplink", { url })),
	/**
	 *  pair_via_ssh — SSH into a remote machine, install/upgrade cinch, and
	 *  authenticate it against the same relay account as the local desktop.
	 * 
	 *  Verification contract (fixes the 0.1.5 silent-success bug):
	 *    1. The local desktop must already be signed in to the target relay.
	 *       Otherwise we cannot tell whether the remote ended up linked to the
	 *       right user_id — abort up front rather than report false success.
	 *    2. The remote script always emits a `<<CINCH-PAIRED-OK>>{...}<<END>>`
	 *       marker on stdout when it considers the remote paired (either it
	 *       reused an existing matching pairing, or it ran a fresh device-code
	 *       login). Without that marker, SSH exit 0 means nothing.
	 *    3. After the SSH process exits, we require the marker to have been
	 *       observed AND its `user_id` to match the local user. A blank or
	 *       mismatching marker becomes a hard error so the UI shows "Setup
	 *       failed" instead of "paired successfully".
	 * 
	 *  In parallel, when the remote emits the legacy `<<CINCH-DEVICE-CODE>>`
	 *  marker (fresh-pair path) we still fire `SshPairMarkerFound` so the
	 *  frontend opens the browser.
	 */
	pairViaSsh: (target: string, relayUrl: string | null, skipInstall: boolean) => typedError<null, string>(__TAURI_INVOKE("pair_via_ssh", { target, relayUrl, skipInstall })),
	// list_ssh_hosts — return concrete aliases from the user's ~/.ssh/config.
	listSshHosts: () => typedError<string[], string>(__TAURI_INVOKE("list_ssh_hosts")),
	/**
	 *  approve_remote_login — accept a pending device-code request and clear it
	 *  from the local pending list.
	 * 
	 *  Calls `POST /auth/device-code/complete` on the relay with bearer auth,
	 *  then removes the matching entry from PendingCodesHandle.
	 */
	approveRemoteLogin: (userCode: string) => typedError<null, string>(__TAURI_INVOKE("approve_remote_login", { userCode })),
	/**
	 *  deny_remote_login — reject a pending device-code request and clear it
	 *  from the local pending list.
	 * 
	 *  Calls `POST /cinch.v1.AuthService/DeviceCodeDeny` (Connect-RPC unary)
	 *  on the relay with bearer auth, then removes the matching entry from
	 *  PendingCodesHandle.
	 */
	denyRemoteLogin: (userCode: string) => typedError<null, string>(__TAURI_INVOKE("deny_remote_login", { userCode })),
	/**
	 *  Pair with a relay using a master token obtained from `cinch auth login`.
	 *  Clears any existing relay and replaces it with the new one.
	 */
	pairWithToken: (req: PairWithTokenRequest) => typedError<PairWithTokenResult, string>(__TAURI_INVOKE("pair_with_token", { req })),
	getLatestVersions: () => __TAURI_INVOKE<LatestVersions>("get_latest_versions"),
	getDeviceVersionStatus: (reported: string | null, clientType: string | null, latest: LatestVersions) => __TAURI_INVOKE<VersionStatus>("get_device_version_status", { reported, clientType, latest }),
	runSelfUpdate: () => typedError<null, string>(__TAURI_INVOKE("run_self_update")),
	/**
	 *  Frontend calls this on the same mousedown that starts the native drag.
	 *  Shows the overlay on the current monitor and spawns a drag-end poll.
	 */
	snapDragStart: () => typedError<null, string>(__TAURI_INVOKE("snap_drag_start")),
};

/** Events */
export const events = {
	authAdoptedFromCli: makeEvent<AuthAdoptedFromCli>("auth-adopted-from-cli"),
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	backgroundHint: makeEvent<BackgroundHint>("background-hint"),
	cliHandoffRequested: makeEvent<CliHandoffRequested>("cli-handoff-requested"),
	clipDecryptFailed: makeEvent<ClipDecryptFailed>("clip-decrypt-failed"),
	clipDeleted: makeEvent<ClipDeleted>("clip-deleted"),
	clipPinned: makeEvent<ClipPinned>("clip-pinned"),
	clipReceived: makeEvent<ClipReceived>("clip-received"),
	clipSent: makeEvent<ClipSent>("clip-sent"),
	deviceCodePending: makeEvent<DeviceCodePending>("device-code-pending"),
	devicesChanged: makeEvent<DevicesChanged>("devices-changed"),
	imageDownloadComplete: makeEvent<ImageDownloadComplete>("image-download-complete"),
	imageDownloadFailed: makeEvent<ImageDownloadFailed>("image-download-failed"),
	latestVersionsUpdated: makeEvent<LatestVersionsUpdated>("latest-versions-updated"),
	newSourceDetected: makeEvent<NewSourceDetected>("new-source-detected"),
	offlineQueueDropped: makeEvent<OfflineQueueDropped>("offline-queue-dropped"),
	remoteClipReceived: makeEvent<RemoteClipReceived>("remote-clip-received"),
	snapGuideUpdate: makeEvent<SnapGuideUpdate>("snap-guide-update"),
	sshPairMarkerFound: makeEvent<SshPairMarkerFound>("ssh-pair-marker-found"),
	trayOpenSettings: makeEvent<TrayOpenSettings>("tray-open-settings"),
	wsStatus: makeEvent<WsStatus>("ws-status"),
};

/* Types */
/**
 *  Fired when the desktop notices that credentials on disk came from the CLI
 *  (the FS watcher observed a credential_version bump while the desktop was
 *  in LocalOnly). The frontend uses this to surface a one-shot toast so the
 *  user knows their CLI sign-in carried over.
 */
export type AuthAdoptedFromCli = {
	user_short: string,
};

export type AuthErrorReason = { kind: "RelayUnreachable" } | { kind: "KeyringUnavailable" } | { kind: "NetworkDown" } | { kind: "InvalidPairToken" };

export type AuthProgress = { kind: "SigningIn" } | { kind: "Pairing" } | { kind: "RotatingToken" };

export type AuthState = { variant: "LocalOnly" } | { variant: "Authenticating"; payload: {
	progress: AuthProgress,
} } | { variant: "Authenticated"; payload: {
	user_id: string,
	device_id: string,
	hostname: string,
	relay_url: string,
	active_relay_id: string,
	machine_id: string,
} } | { variant: "ErrorRecoverable"; payload: {
	reason: AuthErrorReason,
	retry_after_ms: number | null,
} };

export type AuthStateChanged = AuthState;

/**
 *  Fired exactly once — the first time the user dismisses the window (close
 *  box / Cmd+W / Cmd+Q) before the background-running hint has been
 *  acknowledged. The Rust side gates emission on the `background_hint_seen`
 *  flag (see `window_manage::request_dismiss`); the React `BackgroundHintDialog`
 *  listens and shows the one-time dialog.
 */
export type BackgroundHint = null;

/**
 *  Fired when the desktop receives a `cinch://login?relay=…&from=cli` deep
 *  link from the CLI's handoff. The React layer responds by opening the
 *  AddRelayDialog with the relay URL pre-filled.
 */
export type CliHandoffRequested = {
	relay_url: string,
};

/**
 *  Fired when a received clip cannot be decrypted (wrong or missing AES key).
 *  The desktop fires retry_key_bundle automatically; this event lets the UI
 *  show a hint so the user knows recovery is in progress.
 */
export type ClipDecryptFailed = {
	clip_id: string,
	// "missing_key" or "tag_failed: <detail>"
	reason: string,
};

export type ClipDeleted = string;

/**
 *  Fired when a clip's pin state changes (from relay WS broadcast or local pin/unpin).
 *  React listens to refresh the pinned-clips list on any device.
 */
export type ClipPinned = {
	clip_id: string,
	is_pinned: boolean,
	pin_note: string | null,
};

export type ClipReceived = LocalClip;

/**
 *  Emitted after an explicit "send current clipboard" attempt. `true` when a
 *  clip was sent, `false` when the clipboard had nothing to send. Drives the
 *  in-app toast.
 */
export type ClipSent = boolean;

export type ConfigInfo = {
	relay_url: string,
	user_id: string,
	hostname: string,
};

export type Device = {
	id?: string,
	hostname?: string,
	source_key?: string,
	clip_count?: number,
	paired_at?: string,
	last_push_at?: string | null,
	online?: boolean,
	nickname?: string,
	public_key?: string,
	public_key_fingerprint?: string,
	machine_id?: string | null,
	/**
	 *  Semver string of the client binary as reported via WS client_hello or
	 *  X-Cinch-Client-Version. Empty if the device has not reported yet.
	 */
	client_version?: string | null,
	/**
	 *  "cli" or "desktop". Determines which GitHub repo's latest release to
	 *  compare against. Empty if not reported.
	 */
	client_type?: string | null,
	// RFC3339 timestamp of the last version report.
	client_version_at?: string | null,
};

/**
 *  Fired when the relay pushes a `device_code_pending` WebSocket message, indicating
 *  that a CLI `cinch auth login --user EMAIL` has started and is awaiting desktop
 *  approval. The React layer uses this event to surface the approval UI.
 */
export type DeviceCodePending = PendingDeviceCode;

/**
 *  Fired when the relay-side device set may have changed: after a successful
 *  rename/revoke/sign_out/pair_with_token/pair_via_ssh from this device, and
 *  on every WS (re)connect (other devices may have paired/revoked while this
 *  desktop was offline). React listens once and re-fetches `list_devices`,
 *  replacing the legacy 5-second polling in `DevicesPanel`.
 */
export type DevicesChanged = null;

export type ImageDownloadComplete = string;

export type ImageDownloadFailed = string;

/**
 *  Latest published release tag for each binary, plus the unix
 *  timestamp at which the desktop last refreshed it. Frontend reads
 *  this verbatim to decide whether to render the "Update" affordance.
 */
export type LatestVersions = {
	cli: string | null,
	desktop: string | null,
	// Unix seconds.
	fetched_at: number | null,
};

/**
 *  Fired when the desktop's background updater refreshes the cached
 *  latest-release tags. React's `useLatestVersions` hook subscribes to
 *  this so version badges re-render the moment the new tag lands,
 *  without waiting for the next mount.
 */
export type LatestVersionsUpdated = LatestVersions;

export type LocalClip = {
	id: string,
	user_id: string,
	content: string,
	content_type: string,
	source: string,
	label: string,
	byte_size: number,
	media_path: string | null,
	created_at: number,
	synced: boolean,
	sync_state: string,
	is_pinned: boolean,
	pin_note: string | null,
	received_at: number,
};

export type NewSourceDetected = string;

/**
 *  Fired when queued offline clips are dropped because the encryption key
 *  is missing. The frontend shows a toast prompting the user to sign in again.
 */
export type OfflineQueueDropped = {
	count: number,
};

export type PairWithTokenRequest = {
	relay_url: string,
	pair_token: string,
	label: string | null,
};

export type PairWithTokenResult = {
	relay_id: string,
	user_id: string,
	device_id: string,
};

/**
 *  A device-code approval request forwarded from the relay via WebSocket.
 *  Derives `specta::Type` so tauri-specta can generate the TypeScript binding.
 */
export type PendingDeviceCode = {
	user_code: string,
	hostname: string,
	source_region: string,
	// Unix timestamp (seconds) when the request arrived at the relay.
	requested_at: number,
};

/**
 *  Fired when a clip arrives from another device via the relay WebSocket
 *  (i.e., delivered by `client_core::sync::Writer`'s on_new_clip callback).
 *  Distinct from `ClipReceived` (which fires for locally-captured clips on
 *  this device) so the React layer can trigger per-source desktop alerts
 *  without a local-vs-remote heuristic.
 */
export type RemoteClipReceived = LocalClip;

/**
 *  Settings-pane retention config (plan 01-06).
 * 
 *  `local_days` = rolling window for the local SQLite cache.
 *  `remote_days` = rolling window for relay-stored clips.
 *  Default is 30 days per D-05; clamp range is `[7, 365]` per V5.
 */
export type RetentionConfig = {
	local_days: number,
	remote_days: number,
};

/**
 *  Streamed to the `snap-overlay` window during a panel drag. All
 *  coordinates are physical pixels relative to the global desktop space;
 *  the overlay subtracts the monitor origin and divides by `scale` to get
 *  CSS-logical coordinates. `visible:false` tells the overlay to clear.
 */
export type SnapGuideUpdate = {
	monitor_x: number,
	monitor_y: number,
	monitor_w: number,
	monitor_h: number,
	scale: number,
	// Anchor top-left (physical).
	anchor_x: number,
	anchor_y: number,
	win_w: number,
	win_h: number,
	within_snap: boolean,
	visible: boolean,
};

export type SourceAlertSetting = {
	source: string,
	alert_enabled: boolean,
};

export type SourceInfo = {
	source: string,
	clip_count: number,
	last_seen: number,
};

export type SourceSetting = {
	source: string,
	auto_copy: boolean,
};

/**
 *  Fired by `pair_via_ssh` when the remote machine's `cinch auth login
 *  --headless` emits the device-code marker. The frontend opens `url`
 *  in a browser so the user can complete OAuth; the command keeps running
 *  until the SSH process exits.
 */
export type SshPairMarkerFound = {
	url: string,
};

/**
 *  Fired when the user clicks the tray's "Settings…" item. React's `App.tsx`
 *  listens and opens the in-app Settings pane (`setShowSettings(true)`).
 */
export type TrayOpenSettings = null;

/**
 *  Display-facing user profile sourced from the active relay profile.
 * 
 *  Returned by [`get_user_profile`]. All fields are empty strings when no
 *  relay profile is configured (graceful pre-auth state).
 */
export type UserProfile = {
	display_name: string,
	email: string,
	identity_provider: string,
	user_id: string,
};

/**
 *  Outcome of comparing a single device's reported version against the
 *  cached latest tag for that client type. Anything we cannot parse or
 *  classify lands in `Unknown` — never `UpToDate` — so the badge stays
 *  neutral until we have real evidence.
 */
export type VersionStatus = "UpToDate" | "Outdated" | "Unknown";

export type WsStatus = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

